name = "mc.starting.cc — Cobblemon + Create (NeoForge 1.21.1)"
author = "mc.starting.cc"
version = "2026-07-23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73fe14c8d33c3652bd2924389733e75507cffc2cd64311978cabaf677ddd3366"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
