name = "mc.starting.cc — Cobblemon + Create (NeoForge 1.21.1)"
author = "mc.starting.cc"
version = "2026-06-29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "580a07b9416745c75c686c7e6147d9175a52bebbec462a5955c1ef008df7aa8d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
