name = "mc.starting.cc — Cobblemon + Create (NeoForge 1.21.1)"
author = "mc.starting.cc"
version = "2026-07-27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b96d4c5fc58cb0016ea550ada7404eebd499c1556f12d4b5a0eecf417825a576"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
